name: Tests 7-8

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Tests
        uses: Yandex-Practicum/test-project-action@v1
        with:
          project: 'zakrivayuschiy-teg-f'
